### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by PKS-formido**

### CODE REVIEW

**Comment by PKS-formido** [comment]
Created a new issue [Cannot access admin functions #2](https://github.com/fssa-batch3/praveenkumar.sekar__web_project/issues/2) in GitHub

**Comment by PKS-formido** [comment]
Created a new issue [Size of the product is not displayed in the cart. #3](https://github.com/fssa-batch3/praveenkumar.sekar__web_project/issues/3) in GitHub

**Comment by PKS-formido** [comment]
Created a new issue [Quantity of Product in cart. #4](https://github.com/fssa-batch3/praveenkumar.sekar__web_project/issues/4) in GitHub

**Comment by JayashreeSelvarangam** [comment]
Created a new issue [In add to cart, the product is getting added more than trice. #5](https://github.com/fssa-batch3/praveenkumar.sekar__web_project/issues/5) in GitHub

**Comment by JayashreeSelvarangam** [comment]
Created a new issue [There is a problem in adding prices in the products which were added to the add to cart. #6](https://github.com/fssa-batch3/praveenkumar.sekar__web_project/issues/6) in GitHub

**Comment by JayashreeSelvarangam** [comment]
Created a new issue [In the admin page , The edit feature is not working properly #7](https://github.com/fssa-batch3/praveenkumar.sekar__web_project/issues/7) in GitHub

**Comment by JayashreeSelvarangam** [comment]
Created a new issue [In edit page ,it is asking that image url field  is compulsory to fill up . #8](https://github.com/fssa-batch3/praveenkumar.sekar__web_project/issues/8) in GitHub

**Comment by JayashreeSelvarangam** [comment]
Created a new issue [The remove feature is not working in the add to cart page. #9](https://github.com/fssa-batch3/praveenkumar.sekar__web_project/issues/9) in GitHub

**Comment by JayashreeSelvarangam** [comment]
Created a new issue [after loging out the header is not get changed to the header which  is supposed to be in before login. #10](https://github.com/fssa-batch3/praveenkumar.sekar__web_project/issues/10) in GitHub

**Comment by JayashreeSelvarangam** [comment]
Created a new issue [The validation details should be mentioned in the form itself for the user #11](https://github.com/fssa-batch3/praveenkumar.sekar__web_project/issues/11) in GitHub

**Comment by JayashreeSelvarangam** [comment]
Created a new issue [After deleting the profile out the header is not get changed to the header which is supposed to be in before login.  #12](https://github.com/fssa-batch3/praveenkumar.sekar__web_project/issues/12) in GitHub

**Pull request closed without merging**
